on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Dotnet install tools 
      run: dotnet tool install --global dotnet-xscgen --version 2.0.878  
      
      
    - name: Dotnet generate class from xsd 
      working-directory: generated/
      run: xscgen -n "|http://crd.gov.pl/wzor/2023/06/29/12648/schemat.xsd=Xml.Schematy.Dziedzinowe.Mf.FA2" http://crd.gov.pl/wzor/2023/06/29/12648/schemat.xsd
      
    - name: Dotnet pack
      run: ls -la
      
    - name: Dotnet pack
      run: dotnet pack -c Release -p:Version=${GITHUB_REF##*/v} 

    - name: Dotnet Nuget Push   
      working-directory: KSeF/KSeF/bin/Release/
      run: dotnet nuget push KSeF.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY_KSEF }}
      continue-on-error: false
